-- MySQL Script generated by MySQL Workbench
-- 12/24/15 09:53:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tanyapryhodko
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tanyapryhodko
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tanyapryhodko` DEFAULT CHARACTER SET utf8 ;
USE `tanyapryhodko` ;

-- -----------------------------------------------------
-- Table `tanyapryhodko`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tanyapryhodko`.`albums` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `active` TINYINT(1) NOT NULL DEFAULT 0,
  `breadcrumb` VARCHAR(45) NOT NULL,
  `font_color` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanyapryhodko`.`languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tanyapryhodko`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanyapryhodko`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tanyapryhodko`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `role` TINYINT(4) NOT NULL DEFAULT 1,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tanyapryhodko`.`albums_texts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tanyapryhodko`.`albums_texts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `languages_id` INT NOT NULL,
  `albums_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_albums_texts_languages_idx` (`languages_id` ASC),
  INDEX `fk_albums_texts_albums1_idx` (`albums_id` ASC),
  CONSTRAINT `fk_albums_texts_languages`
    FOREIGN KEY (`languages_id`)
    REFERENCES `tanyapryhodko`.`languages` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_texts_albums1`
    FOREIGN KEY (`albums_id`)
    REFERENCES `tanyapryhodko`.`albums` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `tanyapryhodko`.`languages`
-- -----------------------------------------------------
START TRANSACTION;
USE `tanyapryhodko`;
INSERT INTO `tanyapryhodko`.`languages` (`id`, `code`, `title`, `enabled`) VALUES (1, 'ru', 'Русский', 1);
INSERT INTO `tanyapryhodko`.`languages` (`id`, `code`, `title`, `enabled`) VALUES (2, 'en', 'English', 1);
INSERT INTO `tanyapryhodko`.`languages` (`id`, `code`, `title`, `enabled`) VALUES (3, 'ar', ' العَرَبِية', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `tanyapryhodko`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `tanyapryhodko`;
INSERT INTO `tanyapryhodko`.`users` (`id`, `username`, `password`, `name`, `role`, `email`) VALUES (DEFAULT, 'tanya_admin', '84334f499b6d57ad9653cd2a16d5b9a0', 'Tanya', 1, 'info@tanyapryhodko.com');

COMMIT;

